# Generated by Django 2.2.3 on 2019-09-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status Post', 'verbose_name_plural': 'Status Posts'},
        ),
    ]
